exclude = [
  "@ref",
  "@[Cc]ite.*",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://cantarella-labs.github.io/StatsPostForecasts.jl/stable/?$",
  "^https://blog.esciencecenter.nl", # due to a certificate error (cf. #556)
  "zenodo.org/badge/DOI/FIXME$"
]

exclude_path = [
  "docs/build"
]
